import Head from 'next/head';
import styles from '../styles/Dashboard.module.css';
import { HiMenuAlt2, HiMenu } from 'react-icons/hi';
import { BsNewspaper } from 'react-icons/bs';
import {MdDashboard} from 'react-icons/md';
import { useState, useEffect } from 'react';
import AsideNav from '../components/AsideNav';
import Nav from '../components/Nav';
import { useRouter } from 'next/router';
import Noticias from '../components/Noticias';
import Redaction from '../components/Redaction';

export default function Dashboard() {

  const { push } = useRouter();

  const [userInfo, setUserInfo] = useState({}); 

  const [session, setSession] = useState(false);
  const [sidebar, setSidebar] = useState(true);
  const [section, setSection] = useState('Dashboard');

  const handleSidebar = () => {
    !sidebar ? setSidebar(true) : setSidebar(false);
  }
  useEffect(() => {
    let token = sessionStorage.getItem('Token');
    let user = JSON.parse(localStorage.getItem('UserData'));

    if (!token) {
      setSession(false)
      push('/');
    }else{
      setSession(true)
      setUserInfo(user)
    }
  }, []);

  const [Bloque, setBloque] = useState('Noticias');

  const handleMenu = (data, artData) => {
    console.log(data, artData)
    setBloque()
    if(artData=== typeof undefined){
      setBloque(data)

    }else{
      setBloque(data);
    }
  };
  

  return (
    <div className={`${!session && 'hidden'}`}>
      <Head>
        <title>Dashboard | Prueba Técnica - El Universo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-top justify-center">
        {/*Sidebar*/}
        <aside className={`${sidebar ? styles.open : styles.close} 
              h-screen bg-slate-800 relative`}>

          <div className={`h-16 bg-sky-500 text-white
              ${sidebar ? 'py-4 px-6 flex items-center justify-center' : 'p-4'} 
            `}>
            <BsNewspaper size={40} className="mx-auto" alt='Administración'/>
            <h1 className={`w-full text-center font-bold text-xl ${!sidebar && 'hidden'}`}>NEWS</h1>
          </div>

          <div className="py-6 text-slate-400 text-center">
            {!sidebar ? <MdDashboard size={35} className='mx-auto'/> : <h2 className='px-4'>Administración</h2>}  
          </div>
          <AsideNav status={sidebar} section={section} handleMenu={handleMenu}/> 
          <footer className='absolute w-full bottom-0 bg-slate-700 text-center py-2 text-slate-400'>CVásconez</footer>
        </aside>
        {/***/}
        {/*Sección de contenidos*/}
        <section className="bg-white w-full h-screen relative overflow-y-auto">
          {/*Header content*/}
          <header className='h-16 px-4 py-2 flex items-center justify-between border-b-2 border-slate-300'>
            <button className="m-2 text-gray-600" title='Menu'
              onClick={handleSidebar}>
              {sidebar ? <HiMenuAlt2 size={35} /> : <HiMenu size={35} />}
            </button>

            <Nav userData={userInfo}/>
          </header>
          {/***/}
          {/*Bloque de contenidos*/}
          <div className="content">
            <div className={Bloque=='Noticias' ? '' : 'hidden'}>
              <Noticias active={Bloque} handleMenu={handleMenu}/>  
            </div>
            <div className={Bloque=='Redacción' ? '' : 'hidden'}>
              <Redaction usuario={userInfo} create={Bloque}/>  
            </div>
          </div>
          {/***/}
        </section>
        {/***/}
      </main>
    </div>
  )
}
