import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Dashboard | Prueba Técnica - El Universo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <aside>
          Saidbar
        </aside>
        <section>
          <header>heading</header>
          <div className="content">content</div>
          <footer>footer</footer>
        </section>
      </main>
    </div>
  )
}
