import Head from 'next/head'
import styles from '../styles/Home.module.css';
import { useEffect } from 'react';
import { useRouter } from 'next/router';

export default function Home({children}) {
  const { push } = useRouter();
  useEffect(()=>{
      let token = sessionStorage.getItem('Token');

      if(!token){
          push('/user/login');
      }else{
        push('/dashboard');
      }
  },[]);
  return (
    <div>
      <Head>
        <title>Prueba Técnica - El Universo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.background + ' h-screen flex items-center justify-center'}>
        {children}
      </div>
    </div>
  )
}